server:
  port: 8080

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: amount-deposit-event
      properties:
        spring:
          json:
            trusted:
              packages: ru.akbirov.*
      isolation-level: read_committed
