server:
  port: 8083
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: amount-widthrawal-event
      properties:
        spring:
          json:
            trusted:
              packages: ru.akbirov.*
      isolation-level: read_committed
