spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9094
      #key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: product-created-events
      properties:
        spring:
          json:
            trusted:
              packages: ru.akbirov.core
  datasource:
    username: test
    password: test
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8081